### ISSUE TITLE
Não acha modulo ao importar Linketrack

### ISSUE THREAD

**Issue by ferezini** [Diaszano/linketrackjs#20]
Esta gerando um erro no import do modulo:

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Projetos\ProjetosPessoais\ComprasRafa\backend\node_modules\linketrackjs\dist\inlinketrackdex.js

Realmente este arquivo q a lib procura não existe

**Comment by Diaszano** [comment]
Olá, mil desculpas! Eu acabei não vendo a tua issue. Eu irei começar uma refatoração no código essa semana e corrigirei esse problema!

**Comment by Diaszano** [comment]
Eu fiz uma atualização e melhorias na biblioteca e ela está totalmente funcional.
